-- MySQL Script generated by MySQL Workbench
-- Sat Oct 29 19:54:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mibasedatos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mibasedatos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mibasedatos` DEFAULT CHARACTER SET utf8 ;
USE `mibasedatos` ;

-- -----------------------------------------------------
-- Table `mibasedatos`.`DatosUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mibasedatos`.`DatosUsuario` (
  `CodigoCorreo` NVARCHAR(50) NOT NULL,
  `Contraseña` NVARCHAR(100) NOT NULL,
  PRIMARY KEY (`CodigoCorreo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
